apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-fakeshop-config
  namespace: orion-prod
  labels:
    app.kubernetes.io/name: fake-shop
    app.kubernetes.io/instance: orion-prod
    app.kubernetes.io/part-of: orion
    app.kubernetes.io/managed-by: platform
  annotations:
    metacortex.io/owner: "platform"
data:
  DB_HOST: "pg.orion-prod.svc"
  DB_NAME: "ecommerce"
  DB_PORT: "5432"
