apiVersion: v1
kind: Secret
metadata:
  name: orion-fakeshop-db
  namespace: orion-prod
  labels:
    app.kubernetes.io/name: fake-shop
    app.kubernetes.io/instance: orion-prod
    app.kubernetes.io/part-of: orion
    app.kubernetes.io/managed-by: platform
  annotations:
    metacortex.io/owner: "platform"
type: Opaque
stringData:
  db-user: "CHANGE_ME"
  db-password: "CHANGE_ME"
