apiVersion: v1
kind: Service
metadata:
  name: orion-fakeshop
  namespace: orion-prod
  labels:
    app.kubernetes.io/name: fake-shop
    app.kubernetes.io/instance: orion-prod
    app.kubernetes.io/part-of: orion
    app.kubernetes.io/managed-by: platform
  annotations:
    metacortex.io/owner: "platform"
spec:
  selector:
    app.kubernetes.io/name: fake-shop
    app.kubernetes.io/instance: orion-prod
  ports:
    - port: 80
      targetPort: 5000
